### ISSUE TITLE
Логика поиска файлов

### ISSUE THREAD

**Issue by kopylovvlad** [rambler-digital-solutions/danger-readme_docs#1]
Выдержка из README.md

> Danger plugin to validate sub README mention in main README file

Но по факту плагин проверяет все ли файлы с расширением `.md` добавленные в `/README.md`
https://github.com/rambler-digital-solutions/danger-readme_docs/blob/df83b548d978e6d4917315b67e8642effd547563/lib/readme_docs/plugin.rb#L29

Мне кажется что механизм должен работать не так. 🤔
Во-первых надо проверять файлы по имени (README или readme). 
Во вторых, readme не обязательно могут быть формата `.md` (https://www.makeareadme.com/#what-should-the-readme-file-be-named https://www.makeareadme.com/#how-should-i-make-it)

**Comment by mikhailushka** [comment]
Думаю, что ты прав 🤔 и тут действительно стоит проверять название, а не расширение файла. Хотя с другой стороны, было бы удобно так же иметь возможность не забыть про другие `md` файлы, но думаю, что это можно сделать отдельной фичей

**Comment by kopylovvlad** [comment]
Тогда уже делать фичу с ignore-list чтобы некоторые `.md` файлы можно было игнорить по каким-либо причинам :)
